spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:xtuXyBCP}
    database: 13
    lettuce:
      pool:
        max-active: 300
  datasource:
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:rm-m5eqdyah37h7a10si6o.mysql.rds.aliyuncs.com}:${DATASOURCE_PORT:3306}/wk_build_demo?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:qdoner_123}
#    password: ${DATASOURCE_PASSWORD:qdoner_123}
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:root}
#    password: ${DATASOURCE_PASSWORD:0c0214e705f57cea}
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:123.56.77.35}:${DATASOURCE_PORT:3306}/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:root}
#    password: ${DATASOURCE_PASSWORD:0c0214e705f57cea}
    url: jdbc:mysql://localhost:3306/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

