spring:
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        prefix: admin
      discovery:
        enabled: true
        ip: 127.0.0.1
        server-addr: 127.0.0.1:8848
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:127.0.0.1}:${SENTINEL_DASHBOARD_PORT:8079}
      datasource:
        flow:
          server-addr: 127.0.0.1:8848
          dataId: ${spring.application.name}-flow-rules
          groupId: SENTINEL_GROUP
          rule-type: flow
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:xtuXyBCP}
    database: 13
    lettuce:
      pool:
        max-active: 300
  datasource:
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:rm-m5eqdyah37h7a10si6o.mysql.rds.aliyuncs.com}:${DATASOURCE_PORT:3306}/wk_build_demo?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:ENC(VAozQTHEyfJ33nHsJjYjxPipugpnRpSO)}
#    password: ${DATASOURCE_PASSWORD:ENC(VAozQTHEyfJ33nHsJjYjxPipugpnRpSO)}
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:localhost}:${DATASOURCE_PORT:3306}/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:root}
#    password: ${DATASOURCE_PASSWORD:0c0214e705f57cea}
#    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:123.56.77.35}:${DATASOURCE_PORT:3306}/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
#    username: ${DATASOURCE_USERNAME:root}
#    password: ${DATASOURCE_PASSWORD:0c0214e705f57cea}
    url: jdbc:mysql://localhost:3306/zhgd_build?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#注意 seata 解析nacosIP时，需要设置nacos的实际IP，即nacos启动成功后展示的IP
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}_tx_group
  config:
    type: nacos
    nacos:
      serverAddr: 127.0.0.1:8848
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848

