spring:
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 8.142.66.146:8848
        file-extension: yaml
        prefix: admin
      discovery:
        enabled: true
        ip: 8.142.66.146
        server-addr: 8.142.66.146:8848
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:8.142.66.146}:${SENTINEL_DASHBOARD_PORT:8079}
      datasource:
        flow:
          server-addr: 8.142.66.146:8848
          dataId: ${spring.application.name}-flow-rules
          groupId: SENTINEL_GROUP
          rule-type: flow
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 13
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:rm-m5eqdyah37h7a10si6o.mysql.rds.aliyuncs.com}:${DATASOURCE_PORT:3306}/wk_build_demo?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: ${DATASOURCE_USERNAME:ENC(VAozQTHEyfJ33nHsJjYjxPipugpnRpSO)}
    password: ${DATASOURCE_PASSWORD:ENC(VAozQTHEyfJ33nHsJjYjxPipugpnRpSO)}
#注意 seata 解析nacosIP时，需要设置nacos的实际IP，即nacos启动成功后展示的IP
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}_tx_group
  config:
    type: nacos
    nacos:
      serverAddr: 8.142.66.146:8848
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 8.142.66.146:8848

