spring:
  cloud:
    nacos:
      config:
        enabled: true
        server-addr: 8.142.66.146:8848
        file-extension: yaml
        prefix: admin
      discovery:
        ip: 39.103.190.45
        enabled: true
        server-addr: 8.142.66.146:8848
    sentinel:
      filter:
        enabled: false
      transport:
        dashboard: ${SENTINEL_DASHBOARD_HOST:8.142.66.146}:${SENTINEL_DASHBOARD_PORT:8079}
      datasource:
        flow:
          server-addr: 8.142.66.146:8848
          dataId: ${spring.application.name}-flow-rules
          groupId: SENTINEL_GROUP
          rule-type: flow

  #rabbitMq
  rabbitmq:
    host: 101.200.143.182 #192.168.0.119 #127.0.0.1
    port: 5672
    username: cloud-dev
    password: cloud-dev


  redis:
    host: ${REDIS_HOST:8.142.66.146}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 13
    lettuce:
      pool:
        max-active: 300
  datasource:
    url: jdbc:${DATASOURCE_DBTYPE:mysql}://${DATASOURCE_HOST:rm-m5eqdyah37h7a10si6o.mysql.rds.aliyuncs.com}:${DATASOURCE_PORT:3306}/wk_build_demo?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: qdoner_123
    password: qdoner_123

# netty-socketio 配置
socketio:
  host: 127.0.0.1
  port: 9898
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
